### ISSUE TITLE
Handle Umlauts correctly

### ISSUE THREAD

**Issue by sveri** [cognitect/transit-clj#24] opened 2015-03-03 13:52 UTC
Currently transit-clj cannot handle umlaute correctly.   
This is the shortest example I can come up with:  

    (require '[cognitect.transit :as transit])
    (import [java.io ByteArrayInputStream ByteArrayOutputStream])
    
    (def out (ByteArrayOutputStream. 4096))
    (def writer (transit/writer out :json))
    (transit/write writer "ü")
    (.toString out)
    => "[\"~#'\",\"Ã¼\"]"

**Comment by jlouis** [comment] 2015-03-05 15:25
Hi,

You have entered an UTF8 umlaut, ü. It has to be encoded in some way on the wire, and its ISO8859-15 representation happens to be Ã¼. So somewhere along the path the encoding is being mangled and translated as being wrong.

**Comment by sveri** [comment] 2015-03-05 15:59
Sorry, I don't understand your comment. Is there anything I could do in a different way to make it work?

**Comment by jlouis** [comment] 2015-03-05 16:10
I'm not sure if this is the intended behavior of the library or not. I'm just pointing out what is happening somewhere on the path. I know too little Clojure to ascertain if this has to do with ByteArrayOutputStreams having a specific encoding, or some odd Java-setting messing up stuff.

**Comment by benkamphaus** [comment] 2015-03-05 16:17
@sveri If you follow up on your example by using transit-clj's reader to decode, you'll see the umlaut is returned correctly:

```
(def in (ByteArrayInputStream. (.toByteArray out)))
(transit/read (transit/reader in :json))
;; "ü"
```

**Comment by timewald** [comment] 2015-03-05 17:06
I can't reproduce this problem. When I run your code in a repl, the
toString output prints an umlaut as expected.

ByteArrayOutputStream has an additional toString that lets you specify a
charset encoding. I'm curious what happens if you use (.toString out
"UTF-8").

Tim-

On Thu, Mar 5, 2015 at 11:17 AM, Ben Kamphaus <notifications@github.com>
wrote:

> @sveri <https://github.com/sveri> If you follow up on your example by
> using transit-clj's reader to decode, you'll see the umlaut is returned
> correctly:
>
> (def in (ByteArrayInputStream. (.toByteArray out)))
> (transit/read (transit/reader in :json))
> ;; "ü"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cognitect/transit-clj/issues/24#issuecomment-77394188>
> .
>



-- 
Datomic Team

**Comment by sveri** [comment] 2015-03-05 17:15
@benkamphaus @timewald  Thank you, both your suggested solutions work for me. So it seems like it is not a bug in transit.
Initially I was using ring-transit <https://github.com/jalehman/ring-transit> and cljs-ajax <https://github.com/JulianBirch/cljs-ajax> to connect backend with frontend.
I wonder whome of them is responsible to decode it correctly, I assume it is ring-transit.
Any suggestions on this?

**Comment by benkamphaus** [comment] 2015-03-05 17:33
Is this getting mangled just in your local environment? I can reproduce this if I set my terminal w/repl instance to a different encoding, e.g. Latin-1 /ISO-8559-1, and that's the output you'll see from:

```
(.toString out "ISO-8859-1"); UTF-8 is correct
;; "[\"~#'\",\"Ã¼\"]"
```

Does it decode to the wrong string encoding somewhere in an application? E.g., it's showing up that way in the frontend? I would think you just need the encoding set to UTF-8 where it's being consumed. The same value should still be an umlaut if the correct encoding is specified:

```
(.toString out "ISO-8859-1")
;; "[\"~#'\",\"Ã¼\"]"
(.toString out "UTF-8");
;; "[\"~#'\",\"ü\"]"
```

**Comment by sveri** [comment] 2015-03-05 18:23
Yea, it shows up 8859-1 encoded in my web application where I am using the bespoken ring-transit and cljs-ajax libraries to fetch data from the backend.
Despite that I see the wrong encoding in my cursive repl and in the `lein repl` environment of my project.

**Comment by dchelimsky** [comment] 2015-07-17 18:28
Closing as the issue is outside this lib.

**Closed by dchelimsky** 2015-07-17 18:28 UTC
